### ISSUE TITLE
12V version

### ISSUE THREAD

**Issue by moritzmhmk** [prusa3d/Heatbed-Mini-PCB#1]
Do you plan to design (and sell) a 12V version?

**Comment by JakoobCZ** [comment]
Hi,
there are several benefits to the 24 V over the 12 V, so I don't think there will be any 12V version in the future. Is there any reason, why would you like to go 12V?

**Comment by moritzmhmk** [comment]
I did use 12V on my corexy printer because it was easier to find a ready to use (no screwing in 230V AC wires) PSU (I did use an SFX one).

I did find a 24V 280 W PSU from Meanwell (GST280A24) that I plan to use now since indeed 24V has many advantages. I did already order a 24V mini Heatbed 😉

Maybe offering a Meanwell PSU with high wattage with a pre build (printed) AC side would allow more people to make the move to 24V 🤷‍♂️

**Comment by JakoobCZ** [comment]
I'm sure as the 3D printing manufacturers will move towards the 24V systems, the amount of compatible power supply units will increase.
